services:
  - type: web
    name: ecommerce-store
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn Ecommerce.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Ecommerce.settings
      - key: PYTHON_VERSION
        value: 3.11.11
